# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tw1KKvcLtcUr4kyLWaDXh6w2umVuprFn
"""

import pandas as pd
import numpy as np

from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

uniform(10,50,(3,3))

"""Dataset"""

data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

dataset=pd.DataFrame(data)

dataset

X=dataset.drop('Target',axis=1)
Y=dataset['Target']

X

X_norm=Normalizer(norm='max').fit_transform(X)

X_norm

Y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(Y),(1,-1)))

Y_norm

"""ANN From Scratch"""

weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
 weight_2=array([[.5],[.1]])

#shape 3 by 2
# weight_1=

weight_1

weight_2

output1=X_norm[0]@weight_1
output1

act_output=sigmoid(output1).numpy()
act_output

pred_output=act_output@weight_2
pred_output

"""Mean Squared Error"""

y_true=Y_norm[0][0]
y_pred=pred_output

y_true

mse(y_true,y_pred).numpy()